feature(repositories): refactor user and itinerary repositorie
Butterfly-Effect-AppsLab/visit-bratislava-be pull request #13
Opened 2020-03-25 18:53 UTC by JozefKysel

Refactor user and itinerary repositories to use native sql queries.

2020-03-26 15:28 UTC, RandomUserIK commented on src/main/java/com/visitbratislavabe/controllers/ItineraryRestController.java
>  	public ItineraryDto getItinerary(@PathVariable Long itineraryId) {
Tu by som tiez potom dal `@PathVariable long itineraryId` miesto `Long`

2020-03-26 15:36 UTC, RandomUserIK requested changes
Ostatne za mna ok - okrem zmeny typu parametra.

2020-03-28 14:11 UTC, JozefKysel commented on src/main/java/com/visitbratislavabe/controllers/ItineraryRestController.java
>  	public ItineraryDto getItinerary(@PathVariable Long itineraryId) {
done

2020-03-28 14:18 UTC, RandomUserIK approved these changes

2020-03-28 14:20 UTC, merged